import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <div className="text-white text-lg font-bold">
              <Link href="/matches">Live Soccer</Link>
            </div>
            <div className="space-x-3">
              <Link href="/matches" className="text-gray-300 hover:text-white">
                홈
              </Link>
              <Link
                href="/community"
                className="text-gray-300 hover:text-white"
              >
                커뮤니티
              </Link>
              <Link
                href="/premium-analysis"
                className="text-gray-300 hover:text-white"
              >
                프리미엄 분석
              </Link>
              <Link href="/support" className="text-gray-300 hover:text-white">
                고객센터
              </Link>
            </div>
          </div>
        </nav>
        <main className="container mx-auto p-4">{children}</main>
      </body>
    </html>
  );
}
